/**
 * DataForm component.
 *
 * Renders a form for creating or editing entity records. The form fields
 * are generated dynamically from the entity's field definitions in the DSL.
 *
 * Modes:
 * - **Create mode** (default): empty form, submits via POST.
 * - **Edit mode**: pre-filled form, submits via PUT. Activated when the URL
 *   contains `?edit={recordId}`.
 *
 * Field type → Input mapping:
 * - uuid     → hidden (auto-generated by backend)
 * - string   → text input
 * - text     → textarea
 * - number   → number input
 * - boolean  → checkbox
 * - date     → date input
 *
 * Usage (via DSL):
 *   { "name": "ProductForm", "type": "form", "entity": "Product",
 *     "fields": ["name", "price"], "actions": ["CreateProduct"] }
 */

import { useEffect, useState } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { useAppStore } from "../store/appStore";
import * as api from "../api/client";
import type { ComponentProps } from "./registry";

export default function DataForm({ component }: ComponentProps) {
  const model = useAppStore((state) => state.model);
  const createRecord = useAppStore((state) => state.createRecord);
  const updateRecord = useAppStore((state) => state.updateRecord);
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  // If ?edit={id} is present, we're in edit mode.
  const editId = searchParams.get("edit");
  const isEditMode = Boolean(editId);

  // Form state: field name → current value.
  const [formData, setFormData] = useState<Record<string, unknown>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Look up the entity definition to get full field metadata (types).
  const entity = model?.entities.find((e) => e.name === component.entity);

  /**
   * In edit mode, fetch the existing record and pre-fill the form.
   */
  useEffect(() => {
    if (!isEditMode || !editId) return;

    const fetchRecord = async () => {
      try {
        const record = await api.getRecord(component.entity, editId);
        setFormData(record);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Failed to load record"
        );
      }
    };

    fetchRecord();
  }, [isEditMode, editId, component.entity]);

  /**
   * Find the table page path for the entity so we can navigate back
   * after successful submission.
   */
  const getTablePagePath = (): string | null => {
    if (!model) return null;
    for (const page of model.pages) {
      for (const compName of page.components) {
        const comp = model.components.find((c) => c.name === compName);
        if (comp?.type === "table" && comp.entity === component.entity) {
          return page.path;
        }
      }
    }
    return null;
  };

  /** Update a single field in the form state. */
  const handleFieldChange = (fieldName: string, value: unknown) => {
    setFormData((prev) => ({ ...prev, [fieldName]: value }));
  };

  /** Submit the form — create or update depending on mode. */
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);

    try {
      if (isEditMode && editId) {
        await updateRecord(component.entity, editId, formData);
      } else {
        await createRecord(component.entity, formData);
      }

      // Navigate back to the table page on success.
      const tablePath = getTablePagePath();
      if (tablePath) {
        navigate(tablePath);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save record");
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!entity) {
    return (
      <div className="component-error">
        Entity "{component.entity}" not found in the app model.
      </div>
    );
  }

  return (
    <div className="data-form-container">
      <h2>{isEditMode ? `Edit ${component.entity}` : `New ${component.entity}`}</h2>

      {error && <div className="form-error">{error}</div>}

      <form onSubmit={handleSubmit} className="data-form">
        {/* Render a form field for each field listed in the component definition. */}
        {component.fields.map((fieldName) => {
          // Get the field's type from the entity definition.
          const fieldDef = entity.fields.find((f) => f.name === fieldName);
          if (!fieldDef) return null;

          return (
            <FormField
              key={fieldName}
              name={fieldName}
              type={fieldDef.type}
              value={formData[fieldName]}
              onChange={(val) => handleFieldChange(fieldName, val)}
            />
          );
        })}

        {/* Submit and cancel buttons */}
        <div className="form-actions">
          <button
            type="submit"
            className="btn btn-primary"
            disabled={isSubmitting}
          >
            {isSubmitting
              ? "Saving..."
              : isEditMode
              ? "Update"
              : "Create"}
          </button>
          <button
            type="button"
            className="btn"
            onClick={() => {
              const tablePath = getTablePagePath();
              if (tablePath) navigate(tablePath);
            }}
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  );
}

// ---------------------------------------------------------------------------
// FormField — renders the appropriate input for a DSL field type
// ---------------------------------------------------------------------------

interface FormFieldProps {
  name: string;
  type: string;
  value: unknown;
  onChange: (value: unknown) => void;
}

/**
 * FormField renders the appropriate HTML input element based on the DSL
 * field type. This is the mapping between DSL types and browser inputs.
 */
function FormField({ name, type, value, onChange }: FormFieldProps) {
  /** Human-readable label from field name (e.g. "firstName" → "First Name"). */
  const label = name.charAt(0).toUpperCase() + name.slice(1);

  switch (type) {
    case "string":
      return (
        <div className="form-field">
          <label htmlFor={name}>{label}</label>
          <input
            id={name}
            type="text"
            value={String(value ?? "")}
            onChange={(e) => onChange(e.target.value)}
            placeholder={`Enter ${name}`}
          />
        </div>
      );

    case "text":
      return (
        <div className="form-field">
          <label htmlFor={name}>{label}</label>
          <textarea
            id={name}
            value={String(value ?? "")}
            onChange={(e) => onChange(e.target.value)}
            placeholder={`Enter ${name}`}
            rows={4}
          />
        </div>
      );

    case "number":
      return (
        <div className="form-field">
          <label htmlFor={name}>{label}</label>
          <input
            id={name}
            type="number"
            step="any"
            value={value !== undefined && value !== null ? String(value) : ""}
            onChange={(e) => onChange(Number(e.target.value))}
            placeholder={`Enter ${name}`}
          />
        </div>
      );

    case "boolean":
      return (
        <div className="form-field form-field--checkbox">
          <label htmlFor={name}>
            <input
              id={name}
              type="checkbox"
              checked={Boolean(value)}
              onChange={(e) => onChange(e.target.checked)}
            />
            {label}
          </label>
        </div>
      );

    case "date":
      return (
        <div className="form-field">
          <label htmlFor={name}>{label}</label>
          <input
            id={name}
            type="date"
            value={String(value ?? "")}
            onChange={(e) => onChange(e.target.value)}
          />
        </div>
      );

    case "uuid":
      // UUID fields are auto-generated — don't render an input.
      return null;

    default:
      // Fallback: render a text input for unknown types.
      return (
        <div className="form-field">
          <label htmlFor={name}>{label}</label>
          <input
            id={name}
            type="text"
            value={String(value ?? "")}
            onChange={(e) => onChange(e.target.value)}
            placeholder={`Enter ${name}`}
          />
        </div>
      );
  }
}
